[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "cd ../.. && pnpm install && pnpm --filter @point-blank/server build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
